### ISSUE TITLE
Simple example

### ISSUE THREAD

**Issue by maxatwork** [sullenor/teatime-components#20]
Current examples are too complex (lots of mystic JSON files and so on). Need a more simple example, something like combined html+js file:

``` (html)
<html>
  <script src="path/to/react"></script>
  <script src="path/to/compiled/library/script"></script>
<body>
  <div id="container"></div>
  <script>
    // render some components here
  </script>
</body>
</html>
```

**Comment by sullenor** [comment]
I'm going to switch to the react-storybook. Hope it will be better with the stories and preview for them.

Small example:
- jsx: https://github.com/sullenor/teatime-components/blob/master/stories/Button.js#L9-L21
- preview: http://sullenor.github.io/teatime-components/?selectedKind=Button&selectedStory=theme%3A%20%60action%60&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-actions%2Factions-panel

Will be available for the version 0.7.0

**Comment by sullenor** [comment]
Presumably I can add a code mirror later.

**Comment by sullenor** [comment]
For now, all the component examples are available via [react-styleguidist](https://github.com/styleguidist/react-styleguidist). Example's code is written on JSX syntax and located in markdown files at the [.story](https://github.com/sullenor/teatime-components/tree/master/.story) folder. Preview contains codemirror with runtime repl.

Check the http://sullenor.github.io/teatime-components/ page. I'm going to publish the fresh version in two days (0.7.0).

**Comment by sullenor** [comment]
Solved with: https://github.com/sullenor/teatime-components#example

**Comment by maxatwork** [comment]
Thanks! 👍
